# Generated by Django 5.1 on 2024-08-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='static/main/no_photo_user.png', upload_to='images/user', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_name',
            field=models.CharField(default='Пользователь', max_length=30, verbose_name='telegram имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Пользователь', max_length=30, verbose_name='имя пользователя'),
        ),
    ]
