# Generated by Django 5.1 on 2024-08-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bb_author_customuser_image_alter_customuser_tg_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_name',
            field=models.CharField(default='@telegram', max_length=30, verbose_name='telegram имя'),
        ),
    ]
