# Generated by Django 5.1 on 2024-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rubric_options_remove_rubric_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Товар'),
        ),
    ]
