# Generated by Django 5.1 on 2024-08-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='images/user', verbose_name='Фото профиля'),
        ),
    ]
