# Generated by Django 5.1 on 2024-08-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_сurrency_alter_bb_is_active_bb_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='сurrency',
            options={'ordering': ['order'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AddField(
            model_name='bb',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='Страна'),
        ),
    ]
