# Generated by Django 5.1 on 2024-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='static/main/no_photo_user.png', upload_to='images/user', verbose_name='Фото профиля'),
        ),
    ]
