# Generated by Django 5.1 on 2024-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_country_name_city_bb_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сurrency',
            new_name='Currency',
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, default='None', max_length=150, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
    ]
