# Generated by Django 5.1 on 2024-08-25 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Избранное_объявление', to='main.bb'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Избранное', to=settings.AUTH_USER_MODEL),
        ),
    ]
