# Generated by Django 5.1 on 2024-08-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_favorite_options_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
